Make INSTALL_DIR overridable
platogo/atoss-cli pull request #15
Opened 2022-10-06 13:01 UTC by peterkrenn

So I can run `INSTALL_DIR=~/.bin ./install.sh`

2022-10-10 07:47 UTC, DaniruKun requested changes

2022-10-10 07:47 UTC, DaniruKun commented on install.sh
> +	curl -L https://github.com/platogo/atoss-cli/releases/latest/download/atoss-cli-standalone.jar > $LOCAL_JAR_FILE
```suggestion
	curl -L https://github.com/platogo/atoss-cli/releases/latest/download/atoss-cli-standalone.jar > "$LOCAL_JAR_FILE"
```

2022-10-10 07:47 UTC, DaniruKun commented on install.sh
> +	mkdir -p $LOCAL_JAR_PATH
```suggestion
	mkdir -p "$LOCAL_JAR_PATH"
```

2022-10-10 07:47 UTC, DaniruKun commented on install.sh
> +	install $LOCAL_JAR_FILE $INSTALL_DIR
```suggestion
	install "$LOCAL_JAR_FILE" $INSTALL_DIR
```

2022-10-11 10:10 UTC, merged

2022-10-13 08:55 UTC, peterkrenn commented
Sorry, I missed that. Otherwise I'd have applied the udpates.